### ISSUE TITLE
user login must be accessible from all pages

### ISSUE THREAD

**Issue by 14Muhammad** [noorahmadll/WADProjectCookEatSleep#1]
![screenshot_2](https://user-images.githubusercontent.com/14924671/48966211-b0aa3600-efee-11e8-8955-0c607d423dbe.jpg)

**Comment by A-dill** [comment]
![image](https://user-images.githubusercontent.com/44522062/49096016-79a48080-f28b-11e8-92d6-ecd0d50181d0.png)

**Comment by A-dill** [comment]
issue resolved of login

**Comment by haseebhere** [comment]
Nice work @A-dill
